'''
Created on Jan 14, 2017

@author: CodeKitty
'''
from evennia import DefaultScript
class BeastStatHandler(DefaultScript):
    def at_script_creation(self):
        self.db.families = ["Anakim","Makara","Namtaru","Eshmaki","Ugallu","Inguma","Talassii"]
        self.db.hungers = ["Tyrant","Collector","Ravager","Nemesis","Predator","Whisper","Enabler"]
        self.db.atavisms = []
        self.db.nightmares = []
        self.db.legends = ['Judgmental','Relentless','Unexpected','Seductive','Vicious','Watchful']
        self.db.lives = ['Parental','Shy','Cautious','Loyal','Honest','Selfless']
        self.db.obcasus = []
        atavisms = self.db.atavisms
        nightmares = self.db.nightmares
        if len(atavisms) == 0:
            atavisms.append(tuple(["Alien Allure","Makara","BtP-123"]))
            atavisms.append(tuple(["Basilisk's Touch","Namtaru","BtP-123"]))
            atavisms.append(tuple(["Cyclopean Streanth","Anakim","BtP-124"]))
            atavisms.append(tuple(["Dragonfire","Eshmaki","BtP-124"]))
            atavisms.append(tuple(["Eye of Heaven","Ugallu","Btp-124"]))
            atavisms.append(tuple(["From the Shadows","Eshmaki","BtP-125"]))
            atavisms.append(tuple(["Heart of the Ocean","Makara","BtP-125"]))
            atavisms.append(tuple(["Infestation","Namtaru","BtP-125"]))
            atavisms.append(tuple(["Limb From Limb","Eshaki","BtP-127"]))
            atavisms.append(tuple(["Looming Presence","Anakim","BtP-127"]))
            atavisms.append(tuple(["Mimir's Wisdom","Anakim","BtP-127"]))
            atavisms.append(tuple(["Monster from the Deep","Makara","BtP-128"]))
            atavisms.append(tuple(["Needs Must","Ugallu","BtP-128"]))
            atavisms.append(tuple(["Relentless Hunter","Eshmaki","BtP-129"]))
            atavisms.append(tuple(["Shadowed Soul","Namtaru","BtP-129"]))
            atavisms.append(tuple(["Siren's Treacherous Song","Makara","BtP-130"]))
            atavisms.append(tuple(["Storm-Lashed","Ugallu","BtP-130"]))
            atavisms.append(tuple(["Titanic Blow","Anakim","BtP-131"]))
            atavisms.append(tuple(["Unbreakable","Namtaru","Btp-131"]))
            atavisms.append(tuple(["Wings of The Raptor","Ugallu","BtP-132"]))
            atavisms.append(tuple(["Alien Mindset","Inguma","BPG-82"]))
            atavisms.append(tuple(["Caught in the Webs","Talassii","BPG-83"]))
            atavisms.append(tuple(["Crushing Coils","Talassii","BPG-83"]))
            atavisms.append(tuple(["Doppelganger","Inguma","BPG-83"]))
            atavisms.append(tuple(["Enemy Within","Inguma","BPG-84"]))
            atavisms.append(tuple(["Illusion of Safety","Talassii","BPG-84"]))
            atavisms.append(tuple(["Lightning Strike","Ugallu","BPG-85"]))
            atavisms.append(tuple(["Plague Bearer","Namtaru","BPG-85"]))
            atavisms.append(tuple(["Ravenous Maw","Makara","BPG-86"]))
            atavisms.append(tuple(["Shadow Stalker","Eshmaki","BPG-86"]))
            atavisms.append(tuple(["Skin Deep","Namtaru","BPG-87"]))
            atavisms.append(tuple(["Smashing Currents","Makara","BPG-87"]))
            atavisms.append(tuple(["Terror's Friend","Anakim","BPG-88"]))
            atavisms.append(tuple(["Death of Light","Eshmaki","BPG-88"]))
            atavisms.append(tuple(["Vengeful Earth","Anakim","BPG-88"]))
            atavisms.append(tuple(["Weakness Exposed","Ugallu","BPG-88"]))
        if len(nightmares) == 0:
            nightmares.append(tuple(["All Your Teeth Are Falling Out","Common","BtP-134"]))
            nightmares.append(tuple(["Behold, My True Form!","Common","BtP-134"]))
            nightmares.append(tuple(["Bugs Everywhere!","Common","BtP-134"]))
            nightmares.append(tuple(["Everything You Do Is Worthless","Common","BtP-135"]))
            nightmares.append(tuple(["Fear Is Contagious","Common","BtP-135"]))
            nightmares.append(tuple(["Flying And Falling","Common","BtP-136"]))
            nightmares.append(tuple(["Run Away","Common","BtP-136"]))
            nightmares.append(tuple(["They are all around you","Common","BtP,136"]))
            nightmares.append(tuple(["You are alone","Common","BtP-136"]))
            nightmares.append(tuple(["You are not alone","Common","BtP-137"]))
            nightmares.append(tuple(["You can't wake up","Common","BtP-137"]))
            nightmares.append(tuple(["You cannot run","Common","BtP-137"]))
            nightmares.append(tuple(["You deserve this","Common","BtP-137"]))
            nightmares.append(tuple(["You must obey","Common","BtP-138"]))
            nightmares.append(tuple(["You will never rest","Common","BtP-138"]))
            nightmares.append(tuple(["You are infected","Vampire","BtP-138"]))
            nightmares.append(tuple(["We know all your secrets","Vampire,Mekhet","BtP-138"]))
            nightmares.append(tuple(["Your rage consumes you","Werewolf","BtP-139"]))
            nightmares.append(tuple(["Your tools betray you","Werwewolf,Iron Masters","BtP-139"]))
            nightmares.append(tuple(["You are better than them","Mage","BtP-139"]))
            nightmares.append(tuple(["The void is waiting","Mage","BtP-140"]))
            nightmares.append(tuple(["Everyone hates you","Promethean","BtP-140"]))
            nightmares.append(tuple(["You cannot kill it","Promethean,Tammuz","BtP-140"]))
            nightmares.append(tuple(["You are lost","Changeling","BtP-140"]))
            nightmares.append(tuple(["You are an imposter","Changeling,Manikin","BtP-141"]))
            nightmares.append(tuple(["Death is a prison","Sin-Eater","BtP-141"]))
            nightmares.append(tuple(["You can't take it with you","Sin-Eater,Bonepicker","BtP-142"]))
            nightmares.append(tuple(["Tabula Rasa","Mummy","BtP-142"]))
            nightmares.append(tuple(["Cursed Object","Mummy,Maa-Kep","BtP-142"]))
            nightmares.append(tuple(["The walls have eyes","Common","BPG-89"]))
            nightmares.append(tuple(["They don't love you","Common","BPG-89"]))
            nightmares.append(tuple(["They put something in your food","Common","BPG-89"]))
            nightmares.append(tuple(["They walk among us","Common","BPG-90"]))
            nightmares.append(tuple(["This is due tomorrow","Common","BPG-90"]))
            nightmares.append(tuple(["We're going down!","Common","BPG-91"]))
            nightmares.append(tuple(["You can't dig it out","Common","BPG-91"]))
            nightmares.append(tuple(["You don't have a face","Common","BPG-91"]))
            nightmares.append(tuple(["You're one of us","Common","BPG-91"]))
            nightmares.append(tuple(["You were never right","Common","BPG-92"]))
            nightmares.append(tuple(["Checking it twice","Changeling,Wizened","BPG-92"]))
            nightmares.append(tuple(["Everything you know is a lie","Mage","BPG-92"]))
            nightmares.append(tuple(["Evil doll","Unfleshed,Promethean","BPG-93"]))
            nightmares.append(tuple(["Family is forever","Vampire","BPG-93"]))
            nightmares.append(tuple(["The water won't last forever","Hunters in Darkness,Werewolf","BPG-93"]))
            nightmares.append(tuple(["You are a meat machine","Promethean","BPG-93"]))
            nightmares.append(tuple(["You have foreseen this","Acanthus,Mage","BPG-94"]))
            nightmares.append(tuple(["You should fade away","Silent,Sin-Eater","BPG-94"]))
            nightmares.append(tuple(["You will be the first against the wall","Carthian,Vampire","BPG-94"]))
            nightmares.append(tuple(["Your struggle won't matter","Torn,Sin-Eater","BPG-94"]))
            nightmares.append(tuple(["You are running out of time","Vampire","BPG-96"]))
            nightmares.append(tuple(["God is testing you","Lancea et Sanctum,Vampire","BPG-96"]))