'''
Created on Jan 16, 2017

@author: CodeKitty
'''
from evennia import DefaultScript
class DemonStatHandler(DefaultScript):
    incarnations = ["Destroyer","Guardian","Messenger","Psychopomp"]
    agendas = ["Inquisitors","Integrators","Saboteurs","Tempters"]
    def at_script_creation(self):
        self.db.embeds = []
        self.db.exploits = []
        self.db.processes = []
        self.db.propulsion = []
        self.db.technologies = []
        self.db.modifications = []
        self.db.embeds = []
        self.db.incarnations = self.incarnations
        self.db.agendas = self.agendas
        embeds = self.db.embeds
        exploits = self.db.exploits
        processes = self.db.processes
        technologies = self.db.technologies
        modifications = self.db.modifications
        propulsions = self.db.propulsion
        modifications.append(tuple(["Armored Plates","DtD-196"]))
        modifications.append(tuple(["Blade Hand","DtD-197"]))
        modifications.append(tuple(["Claws and Fangs","DtD-197"]))
        modifications.append(tuple(["Electrical Sight","DtD-197"]))
        modifications.append(tuple(["EMP Field","DtD-197"]))
        modifications.append(tuple(["Fast Attack","DtD-197"]))
        modifications.append(tuple(["Huge Size","DtD-197"]))
        modifications.append(tuple(["Inhuman Intelligence","DtD-197"]))
        modifications.append(tuple(["Inhuman Strength","DtD-198"]))
        modifications.append(tuple(["Inhuman Reflexes","DtD-198"]))
        modifications.append(tuple(["Mental Resistance","DtD-198"]))
        modifications.append(tuple(["Night Vision","DtD-198"]))
        modifications.append(tuple(["Rivet Arm","DtD-198"]))
        modifications.append(tuple(["Sense the Angelic","DtD-198"]))
        modifications.append(tuple(["Slippery Body","DtD-198"]))
        modifications.append(tuple(["Sonic Acuity","DtD-199"]))
        modifications.append(tuple(["Spurs","DtD-199"]))
        modifications.append(tuple(["Tough as Stone","DtD-199"]))
        technologies.append(tuple(["Acidic Spit","DtD-199"]))
        technologies.append(tuple(["Aura Sight","DtD-199"]))
        technologies.append(tuple(["Barbed Tail","DtD-200"]))
        technologies.append(tuple(["Blind Sense","DtD-200"]))
        technologies.append(tuple(["Clairvoyant Sense","DtD-200"]))
        technologies.append(tuple(["Demonic Horns","DtD-201"]))
        technologies.append(tuple(["Electrical Jolt","DtD-201"]))
        technologies.append(tuple(["Electrical Resistance","DtD-201"]))
        technologies.append(tuple(["Environmental Resistance","DtD-202"]))
        technologies.append(tuple(["Essence Drain","DtD-202"]))
        technologies.append(tuple(["Fire Resistance","DtD-202"]))
        technologies.append(tuple(["Frost Aura","DtD-202"]))
        technologies.append(tuple(["Fluid Form","DtD-202"]))
        technologies.append(tuple(["Inhuman Beauty","DtD-202"]))
        technologies.append(tuple(["Glory and Terror","DtD-203"]))
        technologies.append(tuple(["Mind Reading","DtD-203"]))
        technologies.append(tuple(["Mirrored Skin","DtD-203"]))
        propulsions.append(tuple(["Long Limbs","DtD-204"]))
        propulsions.append(tuple(["Phasing","DtD-204"]))
        propulsions.append(tuple(["Plasma Drive","DtD-204"]))
        propulsions.append(tuple(["Spatial Distortion","DtD-204"]))
        propulsions.append(tuple(["Teleport","DtD-204"]))
        propulsions.append(tuple(["Tether","DtD-204"]))
        propulsions.append(tuple(["Wings","DtD-204"]))
        processes.append(tuple(["Aegis Protocol","DtD-205"]))
        processes.append(tuple(["Body Modification","DtD-205"]))
        processes.append(tuple(["Cavernous Maw","DtD-205"]))
        processes.append(tuple(["Corruption Aura","DtD-205"]))
        processes.append(tuple(["Extra Mechanical Limbs","DtD-206"]))
        processes.append(tuple(["Insect Swarm","DtD-206"]))
        processes.append(tuple(["Magnesium Flare","DtD-206"]))
        processes.append(tuple(["Memory Theft","DtD-207"]))
        processes.append(tuple(["Multiple Images","DtD-207"]))
        processes.append(tuple(["Quill Burst","DtD-207"]))
        processes.append(tuple(["Rain of Fire","DtD-208"]))
        processes.append(tuple(["Voice of the Angel","DtD-208"]))
        processes.append(tuple(["Wound Healing","DtD-209"]))
        embeds.append(tuple(["Cacophony","DtD-125","Bystander Effect"]))
        embeds.append(tuple(["Cacophony","DtD-125","Cause and Effect"]))
        embeds.append(tuple(["Cacophony","DtD-126","Combustion"]))
        embeds.append(tuple(["Cacophony","DtD-126","Cool Heads Prevail"]))
        embeds.append(tuple(["Cacophony","DtD-126","Deafen"]))
        embeds.append(tuple(["Cacophony","DtD-126","Devil's Advocate"]))
        embeds.append(tuple(["Cacophony","DtD-127","Hesitation"]))
        embeds.append(tuple(["Cacophony","DtD-128","Hush"]))
        embeds.append(tuple(["Cacophony","DtD-129","Just Bruised"]))
        embeds.append(tuple(["Cacophony","DtD-129","Knockout Punch"]))
        embeds.append(tuple(["Cacophony","DtD-129","Left or Right?"]))
        embeds.append(tuple(["Cacophony","DtD-129","Lucky Break"]))
        embeds.append(tuple(["Cacophony","DtD-130","Merciless Gunman"]))
        embeds.append(tuple(["Cacophony","DtD-130","No Quarter"]))
        embeds.append(tuple(["Cacophony","DtD-131","On the mend"]))
        embeds.append(tuple(["Cacophony","DtD-131","Raw Materials"]))
        embeds.append(tuple(["Cacophony","DtD-131","Sabotage"]))
        embeds.append(tuple(["Cacophony","DtD-131","Shatter"]))
        embeds.append(tuple(["Cacophony","DtD-132","Shifty Eyes"]))
        embeds.append(tuple(["Cacophony","DtD-132","Special Someone"]))
        embeds.append(tuple(["Instrumental","DtD-132","Ambush"]))
        embeds.append(tuple(["Instrumental","DtD-133","Check Backdrop"]))
        embeds.append(tuple(["Instrumental","DtD-133","Download Knowledge"]))
        embeds.append(tuple(["Instrumental","DtD-133","Efficiency"]))
        embeds.append(tuple(["Instrumental","DtD-133","Ellipses"]))
        embeds.append(tuple(["Instrumental","DtD-134","Freeze Assets"]))
        embeds.append(tuple(["Instrumental","DtD-135","Fulcrum Point"]))
        embeds.append(tuple(["Instrumental","DtD-135","Fungible Knowledge"]))
        embeds.append(tuple(["Instrumental","DtD-135","Like I Built It"]))
        embeds.append(tuple(["Instrumental","DtD-136","The map is not the territory"]))
        embeds.append(tuple(["Instrumental","DtD-136","Miles Away"]))
        embeds.append(tuple(["Instrumental","DtD-136","Momentum"]))
        embeds.append(tuple(["Instrumental","DtD-137","Read Hostility"]))
        embeds.append(tuple(["Instrumental","DtD-137","Right Tools for the Job"]))
        embeds.append(tuple(["Instrumental","DtD-137","Shift Consequence"]))
        embeds.append(tuple(["Instrumental","DtD-138","Strike First"]))
        embeds.append(tuple(["Instrumental","DtD-138","Synthesis"]))
        embeds.append(tuple(["Instrumental","DtD-138","Tag and Release"]))
        embeds.append(tuple(["Instrumental","DtD-139","Tools into Toys"]))
        embeds.append(tuple(["Instrumental","DtD-139","Turn Blade"]))
        embeds.append(tuple(["Mundane","DtD-139","Alibi"]))
        embeds.append(tuple(["Mundane","DtD-140","Authorized"]))
        embeds.append(tuple(["Mundane","DtD-140","Cuckoo's Egg"]))
        embeds.append(tuple(["Mundane","DtD-140","Diversion"]))
        embeds.append(tuple(["Mundane","DtD-141","Don't I know you?"]))
        embeds.append(tuple(["Mundane","DtD-142","Earworm"]))
        embeds.append(tuple(["Mundane","DtD-142","Homogenous Memory"]))
        embeds.append(tuple(["Mundane","DtD-142","Identity Theft"]))
        embeds.append(tuple(["Mundane","DtD-143","Idle Conversation"]))
        embeds.append(tuple(["Mundane","DtD-143","In my pocket"]))
        embeds.append(tuple(["Mundane","DtD-144","Interference"]))
        embeds.append(tuple(["Mundane","DtD-144","Last place you look"]))
        embeds.append(tuple(["Mundane","DtD-145","Living Recorder"]))
        embeds.append(tuple(["Mundane","DtD-145","Lost in the crowd"]))
        embeds.append(tuple(["Mundane","DtD-145","Meaningless"]))
        embeds.append(tuple(["Mundane","DtD-146","Never Here"]))
        embeds.append(tuple(["Mundane","DtD-146","Occam's Razor"]))
        embeds.append(tuple(["Mundane","DtD-146","Quick Change"]))
        embeds.append(tuple(["Mundane","DtD-147","Unperson"]))
        embeds.append(tuple(["Mundane","DtD-147","Without a trace"]))
        embeds.append(tuple(["Vocal","DtD-148","Across a crowded room"]))
        embeds.append(tuple(["Vocal","DtD-148","Animal Communication"]))
        embeds.append(tuple(["Vocal","DtD-148","Animal Messenger"]))
        embeds.append(tuple(["Vocal","DtD-149","Borrowed Expertise"]))
        embeds.append(tuple(["Vocal","DtD-149","Common Misconception"]))
        embeds.append(tuple(["Vocal","DtD-149","Eavesdrop"]))
        embeds.append(tuple(["Vocal","DtD-150","Everybody knows"]))
        embeds.append(tuple(["Vocal","DtD-150","Find the leak"]))
        embeds.append(tuple(["Vocal","DtD-150","Freudian Slip"]))
        embeds.append(tuple(["Vocal","DtD-151","Heart's Desire"]))
        embeds.append(tuple(["Vocal","DtD-151","Mercury Retrograde"]))
        embeds.append(tuple(["Vocal","DtD-152","Muse"]))
        embeds.append(tuple(["Vocal","DtD-152","Recurring Hallucinations"]))
        embeds.append(tuple(["Vocal","DtD-153","Social Dynamics"]))
        embeds.append(tuple(["Vocal","DtD-153","Special Message"]))
        embeds.append(tuple(["Vocal","DtD-154","Tower of babel"]))
        embeds.append(tuple(["Vocal","DtD-154","Trick of the light"]))
        embeds.append(tuple(["Vocal","DtD-155","Trust no one"]))
        embeds.append(tuple(["Vocal","DtD-155","Voice of the machine"]))
        exploits.append(tuple(["Addictive Presence","DtD-158","Across a Crowded Room/Freudian Slip"]))
        exploits.append(tuple(["Affliction","DtD-159","Deafen/Recurring Hallucinations"]))
        exploits.append(tuple(["Allies into Gold","DtD-159","Fungible Knowledge/Trust No One"]))
        exploits.append(tuple(["Animate","DtD-161","Fulcrum Point/Sabotage"]))
        exploits.append(tuple(["Behind the curtain","DtD-161","Interference/Last place you look"]))
        exploits.append(tuple(["Break to heal","DtD-162","On the mend/Shift consequence"]))
        exploits.append(tuple(["Deep Pockets","DtD-163","Authorized/In my pocket"]))
        exploits.append(tuple(["Demon House","DtD-163","Hush","Like I built it"]))
        exploits.append(tuple(["Disintegrate","DtD-164","Shatter/Tools into toys"]))
        exploits.append(tuple(["Echoing Death","DtD-164","Turn Blade/Without a trace"]))
        exploits.append(tuple(["Ephemeral Cover","DtD-165","Knockout Punch/Tag and release"]))
        exploits.append(tuple(["Everybody hates him","DtD-165","Mercury retrograde/Special someone"]))
        exploits.append(tuple(["Extispicy","DtD-165","Cause and effect/Read hostility"]))
        exploits.append(tuple(["Force Relationship","DtD-165","Homogenous Memory/Shfity Eyes"]))
        exploits.append(tuple(["Four Minutes Ago","DtD-166","Never Here/Quick Change"]))
        exploits.append(tuple(["Frozen in time","DtD-166","Ellipses/Living recorder"]))
        exploits.append(tuple(["Halo","DtD-167","Bystander effect/Heart's desire"]))
        exploits.append(tuple(["Hellfire","DtD-167","Check Backdrop/Merciless Gunman"]))
        exploits.append(tuple(["Hellhounds","DtD-167","Animal Messenger/Right tools for the job"]))
        exploits.append(tuple(["Incendiary","DtD-168","Combustion/Raw materials"]))
        exploits.append(tuple(["Inflict Stigmata","DtD-168","Find the leak/Muse"]))
        exploits.append(tuple(["Living Shadow","DtD-169","Eavesdrop/Miles away"]))
        exploits.append(tuple(["Merge","DtD-169","Borrowed expertise/Download knowledge"]))
        exploits.append(tuple(["Murder by improbability","DtD-170","Lucky break/Strike first"]))
        exploits.append(tuple(["Play on words","DtD-170","Common Misconception/Meaningless"]))
        exploits.append(tuple(["Posession","DtD-171","Ambush/Momentum"]))
        exploits.append(tuple(["Rain of blood","DtD-172","Cuckoo's Egg/Tower of Babel"]))
        exploits.append(tuple(["Raise dead","DtD-173","Alibi/Just bruised"]))
        exploits.append(tuple(["Raze Infrastructure","DtD-173","Freeze assets/The map is not the territory"]))
        exploits.append(tuple(["Reality enforcement","DtD-173","Hesitation/Occam's razor"]))
        exploits.append(tuple(["Riot","DtD-174","Devil's advocate/No quarter"]))
        exploits.append(tuple(["Rip the Gates","DtD-174","Synthesis/Voice of the machine"]))
        exploits.append(tuple(["Sermon","DtD-175","Everybody knows/Social dynamics"]))
        exploits.append(tuple(["Solitary confinement","DtD-176","Identity theft/Unperson"]))
        exploits.append(tuple(["Stalking Horse","DtD-176","Idle conversation/Lost in the crowd"]))
        exploits.append(tuple(["Stimulus/Response","DtD-176","Don't I know you?/Marco Polo"]))
        exploits.append(tuple(["Summon","DtD-177","Left or right?/Trick of the light"]))
        exploits.append(tuple(["Swarm","DtD-177","Animal Communication/Diversion"]))
        exploits.append(tuple(["Swift Resolution","DtD-178","Cool heads prveail/efficiency"]))
        exploits.append(tuple(["The Word","DtD-179","Earworm/Special message"]))